DROP USER KIMMYEONGHOE CASCADE;

CREATE USER kimmyeonghoe IDENTIFIED BY kimmyeonghoe DEFAULT TABLESPACE USERS;
GRANT CONNECT, RESOURCE TO kimmyeonghoe;

CREATE SEQUENCE KIMMYEONGHOE.CLOTH_CLOTHNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.CLOPUR_CLOPURNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.PURCHASE_PURCHASENUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.REVIEW_REVIEWNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.FAQ_FAQNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.NOTICE_NOTICENUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.QUESTION_QUESTIONNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.TERM_TERMNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.IMAGE_IMAGENUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.LOGO_LOGONUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE SEQUENCE KIMMYEONGHOE.BANNER_BANNERNUM_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
NOCACHE
NOCYCLE;

CREATE TABLE KIMMYEONGHOE.USERS (
USER_ID VARCHAR2(15) CONSTRAINT USER_USERID_PK primary key,
USER_PW varchar2(15) CONSTRAINT USER_USERPW_NN NOT NULL,
USER_NAME VARCHAR2(10) CONSTRAINT USER_USERNAME_NN NOT NULL,
BIRTHDAY DATE CONSTRAINT USER_BIRTHDAY_NN NOT NULL,
CONTACT VARCHAR2(13) CONSTRAINT USER_CONTACT_NN NOT NULL,
EMAIL VARCHAR2(20) CONSTRAINT USER_EMAIL_NN NOT NULL,
POSTCODE VARCHAR2(8),
ADDRESS VARCHAR2(100),
ADDRESS_DETAIL VARCHAR2(100),
JOIN_DATE DATE CONSTRAINT USER_JOINDATE_NN NOT NULL,
WITHDRAWAL_DATE DATE);

CREATE TABLE KIMMYEONGHOE.REVIEWS (
REVIEW_NUM NUMBER CONSTRAINT REVIEW_REVIEWNUM_PK PRIMARY KEY,
TITLE VARCHAR2(100) CONSTRAINT REVIEW_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT REVIEW_CONTENT_NN NOT NULL,
SCORE NUMBER CONSTRAINT REVIEW_SCORE_NN NOT NULL,
USER_ID VARCHAR2(15),
CONSTRAINT REVIEW_USERID_FK FOREIGN KEY(USER_ID)
    REFERENCES KIMMYEONGHOE.USERS(USER_ID)
);

CREATE TABLE KIMMYEONGHOE.QUESTIONS (
QUESTION_NUM NUMBER CONSTRAINT QUESTION_QUESTIONNUM_PK PRIMARY KEY,
TITLE VARCHAR2(100) CONSTRAINT QUESTION_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT QUESTION_CONTENT_NN NOT NULL,
REG_DATE DATE CONSTRAINT QUESTION_REGDATE_NN NOT NULL,
ANSWER_CONTENT VARCHAR2(1000),
USER_ID VARCHAR2(15),
CONSTRAINT QUESTION_USERID_FK FOREIGN KEY(USER_ID)
    REFERENCES KIMMYEONGHOE.USERS(USER_ID)
);

CREATE TABLE KIMMYEONGHOE.NOTICES (
NOTICE_NUM NUMBER CONSTRAINT NOTICE_NOTICENUM_PK PRIMARY KEY,
TITLE VARCHAR2(100) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
REG_DATE DATE CONSTRAINT NOTICE_REGDATE_NN NOT NULL);

CREATE TABLE KIMMYEONGHOE.IMAGES (
IMAGE_NUM NUMBER CONSTRAINT IMAGE_IMAGENUM_PK PRIMARY KEY,
FILE_NAME VARCHAR2(100) CONSTRAINT IMAGE_FILENAME_NN NOT NULL,
STORED_NAME VARCHAR2(50) CONSTRAINT IMAGE_STOREDNAME_NN NOT NULL,
FILE_SIZE NUMBER CONSTRAINT IMAGE_FILESIZE_NN NOT NULL,
REG_DATE DATE CONSTRAINT IMAGE_REGDATE_NN NOT NULL
);

CREATE TABLE KIMMYEONGHOE.LOGOS (
LOGO_NUM NUMBER CONSTRAINT LOGO_LOGONAME_PK PRIMARY KEY,
LOGO_NAME VARCHAR2(100) CONSTRAINT LOGO_LOGONAME_NN NOT NULL,
STORED_NAME VARCHAR2(50) CONSTRAINT LOGO_STOREDNAME_NN NOT NULL,
REG_DATE DATE CONSTRAINT LOGO_REGDATE_NN NOT NULL,
IMAGE_NUM NUMBER,
CONSTRAINT LOGO_IMAGENUM_FK FOREIGN KEY(IMAGE_NUM)
    REFERENCES KIMMYEONGHOE.IMAGES(IMAGE_NUM)
);

CREATE TABLE KIMMYEONGHOE.BANNERS (
BANNER_NUM NUMBER CONSTRAINT BANNER_BANNERNAME_PK PRIMARY KEY,
BANNER_NAME VARCHAR2(10) CONSTRAINT BANNER_BANNERNAME_NN NOT NULL,
REG_DATE DATE CONSTRAINT BANNER_REGDATE_NN NOT NULL);

CREATE TABLE KIMMYEONGHOE.MAILS (
MAIL_NUM NUMBER CONSTRAINT MAIL_MAILNUM_PK PRIMARY KEY,
TITLE VARCHAR2(100) CONSTRAINT MAIL_TITLE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT MAIL_CONTENT_NN NOT NULL);

CREATE TABLE KIMMYEONGHOE.TERMS (
TERM_NUM NUMBER CONSTRAINT TERM_TERMNUM_PK PRIMARY KEY,
CONTENT VARCHAR2(1000) CONSTRAINT TERM_CONTENT_NN NOT NULL,
REG_DATE DATE CONSTRAINT TERM_REGDATE_NN NOT NULL);

CREATE TABLE KIMMYEONGHOE.PURCHASES (
PURCHASE_NUM NUMBER CONSTRAINT PURCHASE_PURCHASENUM_PK PRIMARY KEY,
PRICE NUMBER CONSTRAINT PURCHASE_PRICE_NN NOT NULL,
DELIVERY_FEE NUMBER CONSTRAINT PURCHASE_DELIVERYFEE_NN NOT NULL,
PURCHASE_DATE DATE CONSTRAINT PURCHASE_PURCHASEDATE_NN NOT NULL,
DELIVERY_STATE VARCHAR2(10) CONSTRAINT PURCHASE_DELIVERYSTATE_NN NOT NULL,
USER_ID VARCHAR2(15),
CONSTRAINT PURCHASE_USERID_FK FOREIGN KEY(USER_ID)
    REFERENCES KIMMYEONGHOE.USERS(USER_ID)
);

CREATE TABLE KIMMYEONGHOE.CLOTHS (
CLOTH_NUM NUMBER CONSTRAINT CLOTH_CLOTHNUM_PK PRIMARY KEY,
KIND VARCHAR2(20) CONSTRAINT CLOTH_KIND_NN NOT NULL,
CLOTH_NAME VARCHAR2(100) CONSTRAINT CLOTH_CLOTHNAME_NN NOT NULL,
PRICE NUMBER CONSTRAINT CLOTH_PRICE_NN NOT NULL,
REG_DATE DATE CONSTRAINT CLOTH_REGDATE_NN NOT NULL,
CONTENT VARCHAR2(1000) CONSTRAINT CLOTH_CONTENT_NN NOT NULL,
IMAGE_NAME VARCHAR2(20) CONSTRAINT CLOTH_IMAGENAME_NN NOT NULL,
DISPLAY_STATE VARCHAR2(10) CONSTRAINT CLOTH_DISPLAYSTATE_NN NOT NULL,
CLOTH_LEVEL VARCHAR2(10) CONSTRAINT CLOTH_CLOTHLEVEL_NN NOT NULL,
QUANTITY NUMBER CONSTRAINT CLOTH_QUANTITY_NN NOT NULL,
COLOR VARCHAR2(10) CONSTRAINT CLOTH_COLOR_NN NOT NULL,
CLOTH_SIZE VARCHAR2(5) CONSTRAINT CLOTH_CLOTHSIZE_NN NOT NULL);

CREATE TABLE KIMMYEONGHOE.CLOTH_PURCHASES (
CLOPUR_NUM NUMBER CONSTRAINT CLOPUR_CLOPURNUM_PK PRIMARY KEY,
CLOTH_NUM NUMBER,
CONSTRAINT CLOPUR_CLOTHNUM_FK FOREIGN KEY(CLOTH_NUM)
    REFERENCES KIMMYEONGHOE.CLOTHS(CLOTH_NUM),
PURCHASE_NUM NUMBER,
CONSTRAINT CLOPUR_PURCHASENUM_FK FOREIGN KEY(PURCHASE_NUM)
    REFERENCES KIMMYEONGHOE.PURCHASES(PURCHASE_NUM),
PURCHASE_AMOUNT NUMBER CONSTRAINT CLOPUR_PURCHASEAMOUNT_NN NOT NULL
);

INSERT INTO KIMMYEONGHOE.USERS(USER_ID, USER_PW, USER_NAME, BIRTHDAY, CONTACT, EMAIL, POSTCODE, ADDRESS, ADDRESS_DETAIL, JOIN_DATE, WITHDRAWAL_DATE)
      values ('admin','admin', '관리자', '2021-01-01','0234567890','admin@efgh.com','111111','경기도 고양시 일산동구 중앙로','상세주소 입니다',sysdate,null);
INSERT INTO KIMMYEONGHOE.USERS(USER_ID, USER_PW, USER_NAME, BIRTHDAY, CONTACT, EMAIL, POSTCODE, ADDRESS, ADDRESS_DETAIL, JOIN_DATE, WITHDRAWAL_DATE)
      values ('user','user', 'user', '2021-01-01','01011111111','user@naver.com','111111','경기도 고양시 일산동구 중앙로','123-456',sysdate,null);
insert into KIMMYEONGHOE.CLOTHS(
CLOTH_NUM, KIND, CLOTH_NAME, PRICE, REG_DATE, 
CONTENT, IMAGE_NAME, DISPLAY_STATE, CLOTH_LEVEL, QUANTITY,COLOR, CLOTH_SIZE)
values (KIMMYEONGHOE.CLOTH_CLOTHNUM_SEQ.nextval, '반팔', '스트라이프 티셔츠', 10000, sysdate,'for examine', '123.jpg', 'display', 'normal', 123, 'yellow', 'XL');
insert into KIMMYEONGHOE.CLOTHS(
CLOTH_NUM, KIND, CLOTH_NAME, PRICE, REG_DATE, 
CONTENT, IMAGE_NAME, DISPLAY_STATE, CLOTH_LEVEL, QUANTITY,COLOR, CLOTH_SIZE)
values (KIMMYEONGHOE.CLOTH_CLOTHNUM_SEQ.nextval, '반팔', '오버핏 티셔츠', 10000, sysdate,'for examine', '123.jpg', 'display', 'normal', 123, 'black', 'L');

insert into  KIMMYEONGHOE.PURCHASES(
PURCHASE_NUM, PRICE, DELIVERY_FEE, PURCHASE_DATE, DELIVERY_STATE, USER_ID
) values (KIMMYEONGHOE.PURCHASE_PURCHASENUM_SEQ.nextval,20000,2500,sysdate,'배송중','user');


insert into  KIMMYEONGHOE.CLOTH_PURCHASES(
CLOPUR_NUM, CLOTH_NUM, PURCHASE_NUM, PURCHASE_AMOUNT) 
values (KIMMYEONGHOE.CLOPUR_CLOPURNUM_SEQ.nextval,1,1,1);
insert into  KIMMYEONGHOE.CLOTH_PURCHASES(
CLOPUR_NUM, CLOTH_NUM, PURCHASE_NUM, PURCHASE_AMOUNT) 
values (KIMMYEONGHOE.CLOPUR_CLOPURNUM_SEQ.nextval,2,1,1);

commit;